src/Entity/Commandes.php
<?php

namespace App\Entity;

use App\Repository\CommandesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: CommandesRepository::class)]
class Commandes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\Email]
    private ?string $userEmail = null;

    #[ORM\Column(length: 250)]
    private ?string $productRefs = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?float $prix_total = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserEmail(): ?string
    {
        return $this->userEmail;
    }

    public function setUserEmail(string $userEmail): static
    {
        $this->userEmail = $userEmail;

        return $this;
    }

    public function getProductRefs(): ?string
    {
        return $this->productRefs;
    }

    public function setProductRefs(string $productRefs): static
    {
        $this->productRefs = $productRefs;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getPrixTotal(): ?float
    {
        return $this->prix_total;
    }

    public function setPrixTotal(float $prix_total): static
    {
        $this->prix_total = $prix_total;

        return $this;
    }
}

src/Form/CommandesType.php
<?php

namespace App\Form;

use App\Entity\Commandes;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('userEmail')
            ->add('product_refs', CollectionType::class, [
                'entry_type' => TextType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'prototype' => true,
                'label' => false,
            ])
            ->add('prix')
            ->add('prix_total');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commandes::class,
        ]);
    }
}

src/Controller/CommandesController.php
<?php

namespace App\Controller;

use App\Entity\Commandes;
use App\Form\CommandesType;
use App\Repository\CommandesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Psr\Log\LoggerInterface;

#[Route('/commandes')]
class CommandesController extends AbstractController
{
    #[Route('/cart', name: 'app_commandes_cart', methods: ['GET'])]
    public function cart(): Response
    {
        return $this->render('shoping-cart.html.twig');
    }

    #[Route('/', name: 'app_commandes_index', methods: ['GET'])]
    public function index(CommandesRepository $commandesRepository): Response
    {
        return $this->render('commandes/index.html.twig', [
            'commandes' => $commandesRepository->findAll(),
        ]);
    }

    private $logger;
    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    #[Route('/new', name: 'app_commandes_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        try {
            $data = json_decode($request->getContent(), true);

            $commande = new Commandes();
            $form = $this->createForm(CommandesType::class, $commande);
            // $form->handleRequest($request);
            $form->submit($data);

            // if ($form->isSubmitted() && $form->isValid()) {
            if ($form->isSubmitted()) {
                $entityManager->persist($commande);
                $entityManager->flush();

                return $this->redirectToRoute('app_commandes_index', [], Response::HTTP_SEE_OTHER);
            }
        } catch (\Exception $e) {
            return $this->redirectToRoute('app_commandes_index', ['rep' => $e]);
        }
        return $this->redirectToRoute('app_commandes_index', ['rep' => 'not pass']);
    }

    #[Route('/{id}', name: 'app_commandes_show', methods: ['GET'])]
    public function show(Commandes $commande): Response
    {
        return $this->render('commandes/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commandes_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commandes $commande, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommandesType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_commandes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commandes/edit.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commandes_delete', methods: ['POST'])]
    public function delete(Request $request, Commandes $commande, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $commande->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($commande);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commandes_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commandes/_delete_form.html.twig
<form method="post" action="{{ path('app_commandes_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
	<button class="btn btn-danger">Delete</button>
</form>

templates/commandes/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commandes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commandes
{% endblock %}

{% block body %}
	<h1>Edit Commandes</h1>
	<br>
	{{ include('commandes/_form.html.twig', {'button_label': 'Update'}) }}

	<a class="btn btn-primary" href="{{ path('app_commandes_index') }}">back to list</a>

	{{ include('commandes/_delete_form.html.twig') }}
{% endblock %}

templates/commandes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commandes index
{% endblock %}

{% block body %}
	{% include "header.html.twig" %}

	<div class="container">
		<h1>Commandes index</h1>
		<br>
		<a class="btn btn-primary" href="{{ path('app_start') }}">retour</a>
		<a class="btn btn-primary" href="{{ path('app_commandes_new') }}">Create new</a>
		<table class="table">
			<thead>
				<tr>
					<th>Id</th>
					<th>UserEmail</th>
					<th>Produits</th>
					<th>Prix</th>
					<th>Prix_total</th>
					<th>actions</th>
				</tr>
			</thead>
			<tbody>
				{% if commandes is not defined %}
					<tr>
						<td colspan="6">no records found</td>
					</tr>
				{% else %}

					{% for commande in commandes %}
						<tr>
							<td>{{ commande.id }}</td>
							<td>{{ commande.userEmail }}</td>
							<td>{{ commande.productRefs }}</td>
							<td>{{ commande.prix }}</td>
							<td>{{ commande.prixTotal }}</td>
							<td>
								<a class="btn btn-primary" href="{{ path('app_commandes_show', {'id': commande.id}) }}">show</a>
								<a class="btn btn-primary" href="{{ path('app_commandes_edit', {'id': commande.id}) }}">edit</a>
							</td>
						</tr>

					{% endfor %}
				{% endif %}
				{% if app.request.query.has('rep') %}
					<ul>
						<li>{{ app.request.query.get('rep') }}</li>
					</ul>
				{% endif %}
			</tbody>
		</tbody>
	</table>
</div>
{% include "footer.html.twig" %}{% endblock %}

templates/commandes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commandes
{% endblock %}

{% block body %}
	<h1>Create new Commandes</h1>
	<br>
	{{ include('commandes/_form.html.twig') }}

	<a class="btn btn-primary" href="{{ path('app_commandes_index') }}">back to list</a>
{% endblock %}

templates/commandes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commandes
{% endblock %}

{% block body %}
	<h1>Commandes</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ commande.id }}</td>
			</tr>
			<tr>
				<th>UserEmail</th>
				<td>{{ commande.userEmail }}</td>
			</tr>
			<tr>
				<th>ProductRefs</th>
				<td>{{ commande.productRefs }}</td>
			</tr>
			<tr>
				<th>Prix</th>
				<td>{{ commande.prix }}</td>
			</tr>
			<tr>
				<th>Prix_total</th>
				<td>{{ commande.prixTotal }}</td>
			</tr>
		</tbody>
	</table>

	<a class="btn btn-primary" href="{{ path('app_commandes_index') }}">back to list</a>

	<a class="btn btn-primary" href="{{ path('app_commandes_edit', {'id': commande.id}) }}">edit</a>

	{{ include('commandes/_delete_form.html.twig') }}
{% endblock %}